services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freelog-api
    depends_on:
      - db
      - azurite
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: freelog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: freelog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: freelog-azurite
    command: >
      azurite-blob
      --blobHost 0.0.0.0
      --blobPort 10000
      --location /data
      --loose
    ports:
      - "10000:10000"
    volumes:
      - azurite:/data
    restart: unless-stopped

volumes:
  pgdata:
  azurite:
